### ISSUE TITLE
The idcheckiosdk is not activated. Look at Idcheckio.activate(...)

### ISSUE THREAD

**Issue by pierre-gancel** [ariadnext/IDCHECK.IO_SDK-example-Flutter#1]
Hi,
I am encountering this error while testing, I followed the ReadMe and SDK appears to be activated,

> an error happened during the capture : CAPTURE_FAILED -
{"type":"NOT_ACTIVATED","code":"null","message":"The idcheckiosdk is not activated. Look at Idcheckio.activate(...)"}

Should I revert to your colleague who provided the credentials ?

![Screenshot_2021-01-13-23-23-40-576_com assurly app](https://user-images.githubusercontent.com/69810198/104517558-849b0600-55f6-11eb-8722-bc3d7bc56719.jpg)

**Comment by Tele582** [comment]
Hello, any update on this???

**Comment by matthieu-legendre-idnow** [comment]
For any issues that concerns the credentials or the license file, please send an email at csm@ariadnext.com.
